name: Run Maven build

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run Maven tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Maven tests
      run: mvn clean test
